"""empty message

Revision ID: 7643c4822388
Revises: 
Create Date: 2021-01-25 17:29:18.762765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7643c4822388'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('user_bio', sa.Text(), nullable=True),
    sa.Column('user_avatar', sa.Text(), nullable=True),
    sa.Column('user_background', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('album', sa.String(length=255), nullable=False),
    sa.Column('written_by', sa.String(length=1000), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('lyrics', sa.Text(), nullable=False),
    sa.Column('song_url', sa.Text(), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('song_icon', sa.Text(), nullable=True),
    sa.Column('song_background_image', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('user_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_Id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_facts', sa.Text(), nullable=False),
    sa.Column('user_Id', sa.Integer(), nullable=False),
    sa.Column('song_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_Id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['user_Id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_comment', sa.Text(), nullable=False),
    sa.Column('user_Id', sa.Integer(), nullable=False),
    sa.Column('song_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_Id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['user_Id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('user_Id', sa.Integer(), nullable=False),
    sa.Column('song_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_Id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['user_Id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('comments')
    op.drop_table('annotations')
    op.drop_table('songs')
    op.drop_table('users')
    # ### end Alembic commands ###
