"""Add lyrics column to Annotation Table

Revision ID: 5b29181d5cce
Revises: 3dc7539617ce
Create Date: 2021-01-30 20:58:18.569981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b29181d5cce'
down_revision = '3dc7539617ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('lyrics', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotations', 'lyrics')
    # ### end Alembic commands ###
