"""empty message

Revision ID: 3dc7539617ce
Revises: 1a8672e5a75f
Create Date: 2021-01-30 13:26:13.198586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc7539617ce'
down_revision = '1a8672e5a75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('annotation', sa.Text(), nullable=False))
    op.add_column('annotations', sa.Column('end', sa.Integer(), nullable=False))
    op.add_column('annotations', sa.Column('start', sa.Integer(), nullable=False))
    op.drop_column('annotations', 'song_facts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('song_facts', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('annotations', 'start')
    op.drop_column('annotations', 'end')
    op.drop_column('annotations', 'annotation')
    # ### end Alembic commands ###
