"""empty message

Revision ID: 1a8672e5a75f
Revises: f0cee02b3e55
Create Date: 2021-01-29 14:10:54.445893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8672e5a75f'
down_revision = 'f0cee02b3e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('annotations', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('comments', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('songs', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('songs', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('votes', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('votes', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'updated')
    op.drop_column('votes', 'created')
    op.drop_column('users', 'updated')
    op.drop_column('users', 'created')
    op.drop_column('songs', 'updated')
    op.drop_column('songs', 'created')
    op.drop_column('comments', 'updated')
    op.drop_column('comments', 'created')
    op.drop_column('annotations', 'updated')
    op.drop_column('annotations', 'created')
    # ### end Alembic commands ###
