"""empty message

Revision ID: e22269fe8d96
Revises: 6bf2424518b1
Create Date: 2021-01-25 16:33:25.185944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22269fe8d96'
down_revision = '6bf2424518b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('album', sa.String(length=255), nullable=False),
    sa.Column('written_by', sa.String(length=1000), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('lyrics', sa.Text(), nullable=False),
    sa.Column('song_url', sa.Text(), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('song_icon', sa.Text(), nullable=True),
    sa.Column('song_background_image', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('user_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_Id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_facts', sa.Text(), nullable=False),
    sa.Column('user_Id', sa.Integer(), nullable=False),
    sa.Column('song_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_Id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['user_Id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_comment', sa.Text(), nullable=False),
    sa.Column('user_Id', sa.Integer(), nullable=False),
    sa.Column('song_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_Id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['user_Id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('user_Id', sa.Integer(), nullable=False),
    sa.Column('song_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_Id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['user_Id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('user_avatar', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('user_background', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('user_bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_bio')
    op.drop_column('users', 'user_background')
    op.drop_column('users', 'user_avatar')
    op.drop_table('votes')
    op.drop_table('comments')
    op.drop_table('annotations')
    op.drop_table('songs')
    # ### end Alembic commands ###
